include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"

linter:
  rules:
     avoid_print: false
     prefer_single_quotes: true
     use_super_parameters: true
     prefer_relative_imports: true