name: target_mate
description: A target calculator for reaching required hours for Toggl time tracker.

publish_to: 'none'

version: 0.7.2+30

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  collection: ^1.18.0
  screwdriver: ^5.4.0
  flutter_screwdriver: ^3.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  encrypted_shared_preferences: ^3.0.1
  get_it: ^7.7.0
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  provider: ^6.1.2
  http: ^1.2.2
  url_launcher: ^6.3.0
  flutter_spinkit: ^5.2.1
  paged_vertical_calendar: ^1.1.8
  awesome_calendar:
    git: https://github.com/BirjuVachhani/awesome_calendar.git
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  adaptive_theme: ^3.6.0
  window_manager: ^0.3.9
  system_tray: ^2.0.3
  package_info_plus: ^8.0.0
  flutter_local_notifications: ^17.2.1+2
  bitsdojo_window: ^0.1.6
  pub_semver: ^2.1.4
  material_color_utilities: ^0.8.0
  chopper: ^8.0.1+1
  logging: ^1.2.0
  path_provider: ^2.1.3
  flutter_animate: ^4.5.0
  image: ^4.2.0
  upgrader: ^10.3.0
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  flutter_markdown: ^0.7.3
  animations: ^2.0.11
  path: ^1.9.0
  win32: ^5.5.1
#  flutter_dynamic_icon: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  mobx_codegen: ^2.6.1
  chopper_generator: ^8.0.1
  msix: ^3.16.7
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  intl: ^0.19.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/app_icons/
    - assets/fonts/
    - assets/vectors/
    - assets/system_tray_icons/
  #    - shorebird.yaml

  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf

scripts: scripts.yaml