name: toggl_target
description: A target calculator for reaching required hours for Toggl time tracker.

publish_to: 'none'

version: 0.1.1+1

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  collection: ^1.17.0
  screwdriver: ^3.1.1
  flutter_screwdriver: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^7.0.1
  get_it: ^7.2.0
  mobx: ^2.1.3+1
  flutter_mobx: ^2.0.6+5
  provider: ^6.0.5
  http: ^0.13.5
  url_launcher: ^6.1.8
  flutter_spinkit: ^5.1.0
  paged_vertical_calendar: ^1.1.5
  awesome_calendar: ^1.1.3
  json_annotation: ^4.8.0
  equatable: ^2.0.5
  adaptive_theme: ^3.1.1
  window_manager: ^0.3.0
  system_tray: ^2.0.2
  package_info_plus: ^3.0.2
  flutter_local_notifications: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Light.ttf
          weight: 400
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900


scripts: scripts.yaml