name: target_mate
description: A target calculator for reaching required hours for Toggl time tracker.

publish_to: 'none'

version: 0.6.1+19

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  intl: ^0.18.1
  collection: ^1.17.1
  screwdriver: ^3.1.1
  flutter_screwdriver: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  encrypted_shared_preferences: ^3.0.1
  get_it: ^7.6.0
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  provider: ^6.0.5
  http: ^0.13.6
  url_launcher: ^6.1.11
  flutter_spinkit: ^5.2.0
  paged_vertical_calendar: ^1.1.6
  awesome_calendar: ^1.1.3
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  adaptive_theme: ^3.2.1
  window_manager: ^0.3.2
  system_tray: ^2.0.3
  package_info_plus: ^3.1.2
  flutter_local_notifications: ^14.0.0+1
  bitsdojo_window: ^0.1.5
  pub_semver: ^2.1.4
  material_color_utilities: ^0.2.0
  chopper: ^6.1.1
  logging: ^1.1.1
  path_provider: ^2.0.15
  flutter_animate: ^4.1.1+1
  image: ^4.0.17
  upgrader: ^6.2.0
  flutter_svg: ^2.0.5
#  flutter_dynamic_icon: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.2
  flutter_lints: ^2.0.1
  build_runner: ^2.4.2
  mobx_codegen: ^2.3.0
  chopper_generator: ^6.0.0
  msix: ^3.11.1
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  intl: ^0.18.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/app_icons/
    - assets/fonts/
    - assets/vectors/
    - assets/system_tray_icons/

  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf

scripts: scripts.yaml