name: target_mate
description: A target calculator for reaching required hours for Toggl time tracker.

publish_to: 'none'

version: 0.6.8+26

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  collection: ^1.18.0
  screwdriver: ^5.3.0
  flutter_screwdriver: ^3.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  encrypted_shared_preferences: ^3.0.1
  get_it: ^7.6.4
  mobx: ^2.2.1
  flutter_mobx: ^2.2.0
  provider: ^6.1.1
  http: ^1.1.0
  url_launcher: ^6.2.1
  flutter_spinkit: ^5.2.0
  paged_vertical_calendar: ^1.1.6
  awesome_calendar: ^1.1.3
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  adaptive_theme: ^3.4.1
  window_manager: ^0.3.7
  system_tray: ^2.0.3
  package_info_plus: ^4.2.0
  flutter_local_notifications: ^16.2.0
  bitsdojo_window: ^0.1.5
  pub_semver: ^2.1.4
  material_color_utilities: ^0.5.0
  chopper: ^7.0.9
  logging: ^1.2.0
  path_provider: ^2.1.1
  flutter_animate: ^4.3.0
  image: ^4.1.3
  upgrader: ^8.3.0
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  flutter_markdown: ^0.6.18+2
  animations: ^2.0.8
#  flutter_dynamic_icon: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0
  chopper_generator: ^7.0.6
  msix: ^3.16.6
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  intl: ^0.18.1
  win32: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/app_icons/
    - assets/fonts/
    - assets/vectors/
    - assets/system_tray_icons/
#    - shorebird.yaml

  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf

scripts: scripts.yaml