name: Android Build

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "11.x"
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Flutter version
        run: flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: Create keystore file
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'release.jks'
          fileDir: './android/keystore/'
          encodedString: ${{ secrets.KEYSTORE_FILE }}
      - name: Create keystore.properties file
        run: |
          echo "${{ secrets.KEYSTORE_PROPERTIES }}" > android/keystore.properties
          cat android/keystore.properties
          ls android/keystore
      - name: Build APK
        run: flutter build apk --release
      - name: Build AAB
        run: flutter build appbundle --release
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: APK
          path: build/app/outputs/flutter-apk/*
          if-no-files-found: error
          retention-days: 5
      - name: Upload AAB
        uses: actions/upload-artifact@v2
        with:
          name: App Bundle
          path: build/app/outputs/bundle/release/app-release.aab
          if-no-files-found: error
          retention-days: 5