name: Release Artifacts

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true

jobs:
  android:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "11.x"
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Flutter version
        run: flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: Create keystore file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'release.jks'
          fileDir: './android/keystore/'
          encodedString: ${{ secrets.KEYSTORE_FILE }}
      - name: Create keystore.properties file
        run: echo "${{ secrets.KEYSTORE_PROPERTIES }}" > android/keystore.properties
      - name: Build APK
        run: flutter build apk --release
      - name: remove SHA
        run: rm build/app/outputs/flutter-apk/app-release.apk.sha1
      - name: Rename APK
        if: ${{ github.event.inputs.tag != null }}
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/TogglTarget-android-${{ github.event.inputs.tag }}.apk
      - name: Rename APK
        if: ${{ github.event.inputs.tag == null }}
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/TogglTarget-android-${{ github.event.release.tag_name }}.apk
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          path: build/app/outputs/flutter-apk/*
          if-no-files-found: error
          retention-days: 5
      - name: Clean up keystore and keystore.properties
        if: ${{ always() }}
        run: |
          rm android/keystore.properties
          rm android/keystore/release.jks

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Flutter version
        run: flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: Build App
        run: flutter build macos
      - name: Verify Build
        run: test -d build/macos/Build/Products/Release/TogglTarget.app
      - name: Install create-dmg
        run: brew install create-dmg
      - name: Create dmg
        run: |
          ./installers/dmg/create.sh
      - name: list files
        run: ls -la build/macos/Build/Products/Release/
      - name: Rename dmg
        if: ${{ github.event.inputs.tag != null }}
        run: mv "TogglTarget.dmg" "TogglTarget-macos-${{ github.event.inputs.tag }}.dmg"
      - name: Rename dmg
        if: ${{ github.event.inputs.tag == null }}
        run: mv "TogglTarget.dmg" "TogglTarget-macos-${{ github.event.release.tag_name }}.dmg"
      - name: Upload Artifacts
        if: ${{ github.event.inputs.tag != null }}
        uses: actions/upload-artifact@v3
        with:
          path: TogglTarget-macos-${{ github.event.inputs.tag }}.dmg
          if-no-files-found: error
          retention-days: 5
      - name: Upload Artifacts
        if: ${{ github.event.inputs.tag == null }}
        uses: actions/upload-artifact@v3
        with:
          path: TogglTarget-macos-${{ github.event.release.tag_name }}.dmg
          if-no-files-found: error
          retention-days: 5

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Flutter version
        run: flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: Build App
        run: flutter build windows
      - name: Build App
        run: flutter build windows
      - name: Setup MSIX configs
        run: dart installers\msix\setup.dart installers\msix\ci.yaml ${{ secrets.WIN_CERT_PASSWORD }}
      - name: Create MSIX Installer
        run: flutter pub run msix:create
      - name: Rename file
        if: ${{ github.event.inputs.tag != null }}
        run: ren TogglTarget.msix TogglTarget-windows-${{ github.event.inputs.tag }}.msix
      - name: Rename file
        if: ${{ github.event.inputs.tag == null }}
        run: ren TogglTarget.msix TogglTarget-windows-${{ github.event.release.tag_name }}.msix
      - name: Upload Artifacts
        if: ${{ github.event.inputs.tag != null }}
        uses: actions/upload-artifact@v3
        with:
          path: TogglTarget-windows-${{ github.event.inputs.tag }}.msix
          if-no-files-found: error
          retention-days: 5
      - name: Upload Artifacts
        if: ${{ github.event.inputs.tag == null }}
        uses: actions/upload-artifact@v3
        with:
          path: TogglTarget-windows-${{ github.event.release.tag_name }}.msix
          if-no-files-found: error
          retention-days: 5

  upload:
    needs: [ android, macos, windows ]
    if: always()
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: dist
      - name: Display structure of downloaded files
        run: ls -R dist
      - name: Upload binaries (for Workflow dispatch)
        if: ${{ github.event.inputs.tag != null }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/artifact/*
          tag: ${{ github.event.inputs.tag }}
          file_glob: true
      - name: Upload binaries (for release)
        if: ${{ github.event.inputs.tag == null }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/artifact/*
          tag: ${{ github.ref }}
          file_glob: true