name: MacOS Build

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Flutter version
        run: flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: Build App
        run: flutter build macos
      - name: Verify Build
        run: test -d build/macos/Build/Products/Release/toggl_target.app
      - name: Install create-dmg
        run: brew install create-dmg
      - name: Create dmg
        run: cd installers/dmg && sh create.sh
      - name: list files
        run: ls -la build/macos/Build/Products/Release/
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TogglTarget
          path: TogglTarget.dmg
          if-no-files-found: error
          retention-days: 5