name: MacOS Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Flutter version
        run: flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: Build App
        run: flutter build macos
      - name: Verify Build
        run: test -d build/macos/Build/Products/Release/toggl_target.app
      - name: Install create-dmg
        run: brew install create-dmg
      - name: Create dmg
        run: cd installers/dmg && sh create.sh
      - name: list files
        run: ls -la build/macos/Build/Products/Release/
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TogglTarget
          path: TogglTarget.dmg
          if-no-files-found: error
          retention-days: 5

  upload:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: dist
      - name: Display structure of downloaded files
        run: ls -R dist
      - name: Upload binaries (for Workflow dispatch)
        if: ${{ github.event.inputs.tag != null }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: ${{ github.event.inputs.tag }}
          file_glob: true
      - name: Upload binaries (for release)
        if: ${{ github.event.inputs.tag == null }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: ${{ github.ref }}
          file_glob: true